[workspace]
members = ["debug-derive"]

[package]
name = "dbg-pls"
version = "0.1.0"
authors = ["Conrad Ludgate <conradludgate@gmail.com>"]
edition = "2018"
description = "Syntax aware pretty-printing debugging"
license = "MIT"
repository = "https://github.com/conradludgate/dbg-pls"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbg-pls-derive = { version = "0.1.0", path = "debug-derive", optional = true }
prettyplease = { version = "0.1", optional = true }
textwrap = { version = "0.15", optional = true }

syn = { version = "1", features = ["full"] }

[features]
default = ["derive", "pretty"]
derive = ["dbg-pls-derive"]
pretty = ["prettyplease", "textwrap"]
